### ISSUE TITLE
Deploying on Netlify

### ISSUE THREAD

**Issue by keenanpayne** [drickna/learnWebDev#1]
How do we feel about deploying the website on Netlify? It's free, easy-to-use, and provides some nice functionality for any lightweight website. 

https://www.netlify.com/

**Comment by drickna** [comment]
Deployed it on Netlify (https://lwd.netlify.com/) though some fonts are working. Here's a working version:
http://www.nelsandereck.com/projects/learnwebdev/

**Comment by drickna** [comment]
Not sure if I'm doing Netlify correctly. Also haven't had a chance to look at it.

**Comment by drickna** [comment]
Resolved.
